### PR TITLE
New script: Saphyr average concentration and CV calculation

### PR DESCRIPTION
**Pull request by idalindegaard**
### Added

New script to calculate average concentration and CV value for Saphyr samples

### Fixed

**Steps to consider while deploying**
- Configuration changes:
- Documentation updates:
- Inform users by email:

### Review:
- [ ] Code approved by
- [ ] Tests executed on stage by:  (Document the test done with screen shots and description.)
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by idalindegaard** [comment]
**Testing the script on stage with positive, negative and zero/no values:**

**All positive values:**
Screenshot 2024-03-20 at 10 40 24

**One negative value:**
Screenshot 2024-03-20 at 10 41 17

**One zero value:**
Screenshot 2024-03-20 at 10 42 06

**One artifact with no values:**
Screenshot 2024-03-20 at 10 42 40

**Three artifacts with no/zero/negative values plus the log file with more information about which sample IDs (and which Concentration 1-3) were affected:**
Screenshot 2024-03-20 at 10 55 57


The tests show that the script counts all artifacts that have no/zero/negative values for any of the Concentrations 1-3 (ng/ul) and lets the user know it, you can read more in the log file about which samples had invalid values. In case this happens, the scripts stops after it has checked all the concentrations and won't continue to calculate the CV och Average concentration (ng/ul)

**Conclusion:** The script works as intended.

**Review by Karl-Svard — APPROVED** [review]
Very nice!! 🔥🔥🔥

I think it's ready for merging. Unless of course you have some other feature you'd like to add first

**Comment by idalindegaard** [comment]
> Very nice!! 🔥🔥🔥
> 
> I think it's ready for merging. Unless of course you have some other feature you'd like to add first

Thanks @Karl-Svard! 😀

It says I have some conflicts that need to be resolved. Do you understand what to do?

**Comment by Karl-Svard** [comment]
Yeah, some of the recent PRs are modifying the same lines in the base.py of the calculate EPPs. But it can easily be fixed in the browser. We can go through it together when you have the time :)

**Pull request merged**
