### PR TITLE
Transfer qPCR dilution EPP

### PR DESCRIPTION
**Pull request by Karl-Svard**
### Added
Transfers the qPCR_dilution.py EPP from clinical_EPPs to cg_lims in addition to some changes regarding how the calculations are performed.

### Fixed

**Steps to consider while deploying**
- Configuration changes:
- Documentation updates:
- Inform users by email:

### Review:
- [ ] Code approved by
- [ ] Tests executed on stage by:  (Document the test done with screen shots and description.)
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by RasmusBurge-CG** [comment]
Test on stage
Screenshot 2022-09-19 at 08 20 31

Results
New scriptLIMS ID   (Submitted Sample) | New script, Concentration | New script, Concentration (nM) | New script, Size (bp) | LIMS ID (Submitted Sample) | Concentration | Concentration (nM) | Size (bp)
-- | -- | -- | -- | -- | -- | -- | --
ACC8812A1 | 9.26E-09 | 9.25974252 | 470 | ACC8812A1 | 9.26E-09 | 9.25974252 | 470
ACC8812A2 | 8.25E-09 | 8.245622 | 470 | ACC8812A2 | 8.25E-09 | 8.245622 | 470
ACC8812A3 | 7.91E-09 | 7.90752264 | 470 | ACC8812A3 | 7.91E-09 | 7.90752264 | 470
ACC8812A4 | 8.13E-09 | 8.12994988 | 470 | ACC8812A4 | 8.13E-09 | 8.12994988 | 470
ACC8812A5 | 8.95E-09 | 8.94832994 | 470 | ACC8812A5 | 8.95E-09 | 8.94832994 | 470
ACC8812A6 | 8.39E-09 | 8.39288036 | 470 | ACC8812A6 | 8.39E-09 | 8.39288036 | 470
ACC8786A1 | 1.02E-08 | 10.1752824 | 470 | ACC8786A1 | 1.02E-08 | 10.1752824 | 470
ACC8821A2 | 1.13E-08 | 11.2689484 | 470 | ACC8821A2 | 1.13E-08 | 11.2689484 | 470
ACC8821A4 | 1.08E-08 | 10.8472239 | 470 | ACC8821A4 | 1.08E-08 | 10.8472239 | 470
ACC8821A5 | 8.71E-09 | 8.70588064 | 470 | ACC8821A5 | 8.71E-09 | 8.70588064 | 470
ACC8821A6 | 9.88E-09 | 9.87900199 | 470 | ACC8821A6 | 9.88E-09 | 9.87900199 | 470
ACC8701A7 | 5.73E-09 | 5.72820961 | 470 | ACC8701A7 | 5.73E-09 | 5.72820961 | 470
ACC8804A1 | 8.51E-09 | 8.51069534 | 470 | ACC8804A1 | 8.51E-09 | 8.51069534 | 470
ACC8805A1 | 7.87E-09 | 7.87450548 | 470 | ACC8805A1 | 7.87E-09 | 7.87450548 | 470
ACC8805A2 | 9.99E-09 | 9.99186864 | 470 | ACC8805A2 | 9.99E-09 | 9.99186864 | 470
ACC8805A3 | 1.01E-08 | 10.0503991 | 470 | ACC8805A3 | 1.01E-08 | 10.0503991 | 470
ACC8806A1 | 7.32E-09 | 7.31502493 | 470 | ACC8806A1 | 7.32E-09 | 7.31502493 | 470
ACC8806A2 | 8.29E-09 | 8.28798952 | 470 | ACC8806A2 | 8.29E-09 | 8.28798952 | 470
ACC8806A3 | 8.84E-09 | 8.84081031 | 470 | ACC8806A3 | 8.84E-09 | 8.84081031 | 470
ACC8806A4 | 8.45E-09 | 8.44582979 | 470 | ACC8806A4 | 8.45E-09 | 8.44582979 | 470
ACC8806A5 | 9.30E-09 | 9.30160286 | 470 | ACC8806A5 | 9.30E-09 | 9.30160286 | 470
ACC8806A6 | 7.60E-09 | 7.5993159 | 470 | ACC8806A6 | 7.60E-09 | 7.5993159 | 470
ACC8806A7 | 8.71E-09 | 8.70599388 | 470 | ACC8806A7 | 8.71E-09 | 8.70599388 | 470
ACC8806A8 | 9.35E-09 | 9.34551503 | 470 | ACC8806A8 | 9.35E-09 | 9.34551503 | 470
ACC8806A9 | 8.96E-09 | 8.95551592 | 470 | ACC8806A9 | 8.96E-09 | 8.95551592 | 470
ACC8806A10 | 9.95E-09 | 9.94831952 | 470 | ACC8806A10 | 9.95E-09 | 9.94831952 | 470
ACC8806A11 | 1.01E-08 | 10.1076424 | 470 | ACC8806A11 | 1.01E-08 | 10.1076424 | 470
ACC8806A12 | 8.25E-09 | 8.24583967 | 470 | ACC8806A12 | 8.25E-09 | 8.24583967 | 470
ACC8806A13 | 1.04E-08 | 10.423074 | 470 | ACC8806A13 | 1.04E-08 | 10.423074 | 470
ACC8806A14 | 8.14E-09 | 8.14039456 | 470 | ACC8806A14 | 8.14E-09 | 8.14039456 | 470
ACC8806A15 | 9.48E-09 | 9.4843226 | 470 | ACC8806A15 | 9.48E-09 | 9.4843226 | 470
ACC8810A1 | 8.69E-09 | 8.69198901 | 470 | ACC8810A1 | 8.69E-09 | 8.69198901 | 470


Identical result between old and new script.

**Comment by RasmusBurge-CG** [comment]
Test on stage:
Using old step, https://clinical-lims.scilifelab.se/clarity/work-complete/178128. In this step we have failed samples and one sample ACC7597A3 that had to be calculated manually.

QC (OLD) | LIMS ID (Submitted Sample) (OLD) | Concentration (OLD) | Concentration (nM) (OLD) | Size (bp) (OLD) | LIMS ID (Submitted Sample) (NEW) | Concentration (NEW) | Concentration (nM) (NEW) | Size (bp) (NEW)
-- | -- | -- | -- | -- | -- | -- | -- | --
Pass | ACC7594A2 | 1.61E-08 | 16.1140128 | 470 | ACC7594A2 | 1.61E-08 | 16.1140128 | 470
Pass | ACC7597A1 | 5.14E-09 | 5.1367673 | 470 | ACC7597A1 | 5.14E-09 | 5.1367673 | 470
Pass | ACC7597A2 | 6.56E-09 | 6.56181846 | 470 | ACC7597A2 | 6.56E-09 | 6.56181846 | 470
  | ACC7597A3 |   |   |   | ACC7597A3 |   |   |  
Fail | ACC7597A4 |   |   |   | ACC7597A4 | 3.54E-10 | 0.35364102 | 470
Fail | ACC7475A7 | 2.43E-10 | 0.24313328 | 470 | ACC7475A7 | 2.43E-10 | 0.24313328 | 470
Fail | ACC7583A5 | 7.18E-11 | 0.0717753 | 470 | ACC7583A5 | 7.18E-11 | 0.0717753 | 470
Fail | ACC7594A3 | 7.39E-11 | 0.07389496 | 470 | ACC7594A3 | 7.39E-11 | 0.07389496 | 470


Identical values except that the new script is able to get concentration for ACC7597A3.

**Comment by idalindegaard** [comment]
Hi, @Karl-Svard! Is it possible to change the size (bp) to 450 instead of 470? This is what they have talked about for the new WGS prep

**Comment by Karl-Svard** [comment]
Yes of course! I have written the code so that this can easliy be changed in the future from the Automations config, by editing the values given in:
`bash -c -l "conda activate cg_lims && lims -c /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid} udf calculate qpcr-dilution -f 'qPCR Result File' --dilution-log {compoundOutputFileLuid2} --size-bp 470 --dilution-threshold 0.4 --d1-dilution-range '2.5,5.0' --d2-dilution-range '0.7,1.5'"`

Will change it to correct values in stage now, and then make the same updates to prod when the script is ready to be merged.

**Comment by idalindegaard** [comment]
> 

Awesome, thanks!

**Pull request closed without merging**
