### PR TITLE
Update aliquot volume EPP

### PR DESCRIPTION
**Pull request by Karl-Svard**
### Changed
- made the "Calculate Aliquot Volume" EPP more general by allowing for custom UDF names as CLI input
- refactored some click options

**Steps to consider while deploying**
- Configuration changes:
- Documentation updates:
- Inform users by email:

### Review:
- [ ] Code approved by
- [ ] Tests executed on stage by:  (Document the test done with screen shots and description.)
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by amandaraud — APPROVED** [review]
👌

**Comment by idalindegaard** [comment]
Tänkte testa denna lite snabbt först :)

**Comment by idalindegaard** [comment]
**Test in the Saphyr workflow, in step Labelling & Staining (Saphyr):**

The script calculates the volumes correctly to get the total volume. There's a known limitation when the concentration is very low and amount needed is high, then we can get negative values for the buffer volume. This issue was fixed when the script was used for the TGA aliquotation, by using another script to get the possible input amount that is available from a sample. 

(For the Saphyr workflow we will fix this later if needed)
Screenshot 2024-03-27 at 12 55 46

**Review by idalindegaard — APPROVED** [review]

**Comment by Karl-Svard** [comment]
### Deployed to production.

### The automation "Calculate Volume" has also been updated.

From:
```
bash -c -l "conda activate cg_lims &&  lims -c  /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid}  udf calculate aliquot-volume"
``` 

To:
```
bash -c -l "conda activate cg_lims &&  lims -c  /home/glsai/.genologics.yaml epps -l {compoundOutputFileLuid0} -p {processLuid}  udf calculate aliquot-volume --concentration-udf 'Concentration' --volume-udf 'Sample Volume (ul)' --buffer-udf 'Volume H2O (ul)' --total-volume-udf 'Total Volume (ul)' --amount-ng-udf 'Amount needed (ng)'"
```

**Pull request merged**
