### PR TITLE
Patch aliquot volumes EPP for 0 ul volumes

### PR DESCRIPTION
**Pull request by Karl-Svard**
### Fixed
- No longer count 0 ul volumes as being too low

**Steps to consider while deploying**
- Configuration changes:
- Documentation updates:
- Inform users by email:

### Review:
- [ ] Code approved by
- [ ] Tests executed on stage by:  (Document the test done with screen shots and description.)
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by Karl-Svard** [comment]
Worked on stage:
Screenshot 2024-10-17 at 10 54 06

**Comment by AbiDalby** [comment]
That is a really good point, I don't think that should ever happen, but we most certainly wouldn't want to miss it if a sample is so highly concentrated the calculation has calculated sample volume at 0.006 or something.

**Comment by idalindegaard** [comment]
Could you make it possible for only the buffer to be 0 ul? but not the sample volume

**Comment by Karl-Svard** [comment]
Yes, that won't be a problem. I'll add that logic!

**Comment by Karl-Svard** [comment]
New behaviour:

Screenshot 2024-10-17 at 14 29 24

**Review by idalindegaard — APPROVED** [review]
👏

**Pull request merged**
