### PR TITLE
Barcode file

### PR DESCRIPTION
**Pull request by mayabrandi**
### Review:
- [x] Code approved by @Mropat 
- [x] Tests executed by @cesve. See the detiailed test doccumentation in https://github.com/Clinical-Genomics/cg_lims/issues/51
- [x] "Merge and deploy" approved by @mayabrandi 

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by Mropat — APPROVED** [review]
:fire: :fire: 
Absolutely fantastic work!!

Only thing I can think of, if the model/headers are going to be reused? In that case, perhaps it could be in some collection module and imported instead of being in same file as the cli EPP command?

**Comment by mayabrandi** [comment]
Good Point. However i think they are super specific to this EPP and therefor should be keept within the script.

**Comment by mayabrandi** [comment]
What do you Think @Mropat

**Review by Mropat — APPROVED** [review]
:+1:

**Pull request merged**
